# Generated by Django 4.0.6 on 2022-10-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbie',
            field=models.CharField(choices=[('1', 'Futbol'), ('2', 'Baloncesto'), ('3', 'Tenis'), ('4', 'Leer'), ('5', 'Cocinar')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_doc',
            field=models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cedula de Extranjeria'), ('PA', 'Pasaporte')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Hobbie',
        ),
    ]
