# Generated by Django 4.0.6 on 2022-10-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_rename_apellidos_user_surnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbie',
            field=models.CharField(choices=[('1', 'Futbol'), ('2', 'Baloncesto'), ('3', 'Tenis'), ('4', 'Leer'), ('5', 'Cocinar')], max_length=10),
        ),
    ]
