# Generated by Django 4.0.6 on 2022-10-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_user_hobbie_alter_user_tipo_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbie',
            field=models.CharField(max_length=50),
        ),
    ]
